
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/devlsy-service1;MODE=mySQL
    url: jdbc:log4jdbc:h2:tcp://localhost/~/devlsy-service1;MODE=mySQL
    username: sa
    password:
#    driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

server:
  port: 9090

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml

