/* 사용자 */
CREATE TABLE "USER_INFO"
   ("USER_NO" NUMBER NOT NULL ENABLE,
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"USER_PASSWORD" VARCHAR2(250) NOT NULL ENABLE,
	"USER_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"USER_EMAIL" VARCHAR2(20) NOT NULL ENABLE,
	"USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"MOD_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "USER_INFO_PK" PRIMARY KEY ("USER_NO", "USER_ID")
)
;
COMMENT ON COLUMN USER_INFO.USER_NO IS '사용자 순번(시퀀스:USER_NO_SEQ)';
COMMENT ON COLUMN USER_INFO.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN USER_INFO.USER_PASSWORD IS '사용자 비밀번호';
COMMENT ON COLUMN USER_INFO.USER_NAME IS '사용자명';
COMMENT ON COLUMN USER_INFO.USER_EMAIL IS '사용자 이메일';
COMMENT ON COLUMN USER_INFO.USE_YN IS '사용여부';
COMMENT ON COLUMN USER_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN USER_INFO.MOD_DATE IS '수정일';
--시퀀스
CREATE SEQUENCE USER_NO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999999 CYCLE NOCACHE ORDER ;