/* 게시판 */
CREATE TABLE "BOARD_INFO"
   ("BOARD_NO" NUMBER NOT NULL ENABLE,
	"TITLE" VARCHAR2(50) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MOD_DATE" DATE, 
	 CONSTRAINT "BOARD_INFO_PK" PRIMARY KEY ("BOARD_NO")
); 
COMMENT ON COLUMN BOARD_INFO.BOARD_NO IS '게시글 순번(시퀀스: BOARD_NO_SEQ)';
COMMENT ON COLUMN BOARD_INFO.TITLE IS '제목';
COMMENT ON COLUMN BOARD_INFO.CONTENT IS '내용';
COMMENT ON COLUMN BOARD_INFO.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN BOARD_INFO.USE_YN IS '사용여부';
COMMENT ON COLUMN BOARD_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN BOARD_INFO.MOD_DATE IS '수정일';
--시퀀스
CREATE SEQUENCE BOARD_NO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999999 CYCLE NOCACHE ORDER ;